### ISSUE TITLE
Wiki update

### ISSUE THREAD

**Issue by justcoding903** [Easy-Coding-Dev/Webdevelopment-header#1]
where is the wiki? 
a wiki should be added 👎

**Comment by EasyCoder-droid** [comment]
> where is the wiki?
> a wiki should be added 👎

Wiki will be added, updates coming soon

**Comment by Easy-Coding-Dev** [comment]
>

**Comment by EasyCoder-droid** [comment]
wiki is online and is working at the moment. wiki will be updated

**Comment by EasyCoder-droid** [comment]
> wiki is online and is working at the moment. wiki will be updated

Wiki Working!
